### ISSUE TITLE
Automatically set different colors for added layers

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/qgis-temporal-profile#14]
When adding new layers to show profiles for, they by default have the same color (red). 

It would be more convenient if they by default got different colors, perhaps randomly chosen from a good color table like [ColorBrewer's Set 1](http://colorbrewer2.org/#type=qualitative&scheme=Set1&n=9)

![image](https://user-images.githubusercontent.com/3404817/33477759-2aa66276-d687-11e7-99d2-30c1f6463c59.png)

**Comment by radosuav** [comment]
Sounds like a good idea! Maybe it would be better to choose colours sequentially form this set to keep some consistency.

**Comment by j08lue** [comment]
Maybe `Paired`, then.

![image](https://user-images.githubusercontent.com/3404817/33571807-789c5c9a-d931-11e7-84ce-6aad41545a88.png)

**Comment by radosuav** [comment]
Implemented in cb4d6c96e1eff746ba3df3ebba4bd58d90b85fb1 (QGIS 2.x) and bd5714284367a2e10477c123ab835af0bf74cba8 (QGIS 3.x).
