### ISSUE TITLE
Plot not displaying

### ISSUE THREAD

**Issue by adehecq** [DHI-GRAS/qgis-temporal-profile#18]
Thanks for creating this nice tool, which is pretty useful !
I was using an old version of QGIS (I think 2.14 or 18) and it was working fine, but now I switched to QGIS 3.8.1 (details on libraries version below) and it doesn't work well anymore. When I click on a band, the Table content seems to display correct values, but there is no graph showing up. When I go to Settings, the "Plot library" tab is empty (see attached screenshot) although Matplotlib is definitely installed. Do you have any idea what the issue is?
Thanks!

QGIS version | 3.8.1-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.9.7 | Running against Qt | 5.9.7
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2dev-CAPI-1.11.2 | Running against GEOS | 3.7.2dev-CAPI-1.11.2 0
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Ubuntu 18.04.3 LTS |   |  

![image](https://user-images.githubusercontent.com/3285905/65317778-bd5ed280-db9c-11e9-959b-e840f4334cad.png)

**Comment by j08lue** [comment]
Thanks for the detailed issue description. I am unable to reproduce this issue in QGIS 3.8.3 **on Windows 10** - Matplotlib is set automatically after plugin install.

I do not have experience with managing packages for QGIS on Linux. Are you sure you have Matplotlib installed for Python 3? (`pip3 freeze` might be relevant?) As far as I can see, the only reason why Matplotlib would not show up in the Settings drop-down menu is that it fails to import:

https://github.com/DHI-GRAS/qgis-temporal-profile/blob/85a0756551562f9839339a88d2ce28f5d19d6ccf/ui/ptdockwidget.py#L48-L52

What do you think, @radosuav?

**Comment by adehecq** [comment]
Ok, I found out what the issue was. I use conda to manage my Python environments, and I had a specific environment for QGIS in which matplotlib was not installed (I guess matplotlib is not a dependency of QGIS). Now that Matplotlib is installed, it works well!
