### ISSUE TITLE
NaN when using a different CRS

### ISSUE THREAD

**Issue by ffilipponi** [DHI-GRAS/qgis-temporal-profile#20]
I am successfull using the 'qgis-temporal-profile' for my research activities. Recently I noted that when QGIS project CRS differs from the raster CRS queried using the plugin, the plugin return values are all NaN.
I suppose this happens because the raster layer is reprojected on the fly in the QGIS view, and that the spatial coordinates queried the QGIS view do not correspond to the spatial coordinates in the raster.
Could you please verify and fix this issue? Thanks for the support and for developing such a useful tool.

**Comment by gc-sommer** [comment]
I've ran into the same issue and fixed it with a pull request https://github.com/DHI-GRAS/qgis-temporal-profile/pull/25

**Comment by gc-sommer** [comment]
As a quick workaround just switch the QGIS project's CRS to the raster layer's CRS.

**Comment by radosuav** [comment]
Will be fixed in version 2.1.0 of the plugin.
