### ISSUE TITLE
netcdf with time dimensions

### ISSUE THREAD

**Issue by espiritocz** [DHI-GRAS/qgis-temporal-profile#22]
hi,

first, thank you for this useful tool!
i cannot use a standard netcdf with standard datetime (time since datetime, in int4). the error goes as
....plottingtool.py", line 153, in attachCurves
    line = wdg.plotWdg.figure.get_axes()[0].plot(xx, yy, gid = profileId)[0]
"float() argument must be a string or a number, not 'real_datetime'"

can you please at least provide an example of netcdf file that should be working fine for "Use NetCDF time dimension" ?

**Comment by j08lue** [comment]
Seems like we use `netcdf.num2date` for converting netCDF time numbers to datetime

https://github.com/DHI-GRAS/qgis-temporal-profile/blob/1be59647c9feda390af558113c4154441720e305/tools/doprofile.py#L282-L284

And this function started not that long ago to return `real_datetime` in some cases, which is a subclass of `datetime.datetime` (this caused issues in other environments, e.g. https://github.com/DHI-GRAS/qgis-temporal-profile/blob/1be59647c9feda390af558113c4154441720e305/tools/doprofile.py#L282-L284).

Seems like this was fixed in Pandas / Xarray (https://github.com/pandas-dev/pandas/issues/23419). We could consider using those libraries to make the datetime conversion more robust. But that would add some non-trivial dependencies. Another way is to make sure that we convert any `cftime` or `datetime.datetime` subclass types to plain `datetime.datetime` before passing them down to Matplotlib etc.

**Comment by j08lue** [comment]
Actually, the package you found @radosuav seems to be the perfect solution here: https://github.com/SciTools/nc-time-axis.

**Comment by espiritocz** [comment]
thank you, this sounds as an easy fix!
yet I think pandas (as pd) would be better option - i have just checked
that both lines correctly output Timestamp:
pd.to_datetime('2015-04-15')
pd.to_datetime(Timestamp('2015-04-15 00:00:00'))



čt 27. 8. 2020 v 14:51 odesílatel Jonas <notifications@github.com> napsal:

**Comment by espiritocz** [comment]
ok, i have just changed the line only to:
profile["l"] = nc.variables["time"][:]

this seems working without error message, but the x axis contains only
numbers (0-1600), no dates


čt 27. 8. 2020 v 15:57 odesílatel Milan Lazecky <espiritocz@gmail.com>
napsal:

**Comment by radosuav** [comment]
@espiritocz I would like avoid making pandas a required package because there is no standard way to handle dependencies of QGIS Python plugins. nc-time-axis is very small and could be bundled together with the plugin. 

Could you try installing nc-time-axis and adding `import nc_time_axis` at the top of plottingtool.py?

**Comment by espiritocz** [comment]
ok,

i have installed it through pip.
i have included the import, opened QGIS, tried some plot - all works fine.
waiting for some updated line to try )

thank you

čt 27. 8. 2020 v 20:40 odesílatel Radoslaw Guzinski <
notifications@github.com> napsal:

**Comment by radosuav** [comment]
Thanks for testing! We will release a new version of the plugin soon, which will include nc_time_axis package, and I might ask you for another quick test.

**Comment by radosuav** [comment]
@espiritocz the updated plugin has just been published. Could you please test it to make sure that all is working fine now and reopen this issue in case it is not.

**Comment by espiritocz** [comment]
thank you Radoslaw.

it works perfectly!

M.


úterý 1. září 2020 Radoslaw Guzinski <notifications@github.com> napsal(a):
> @espiritocz the updated plugin has just been published. Could you please
test it to make sure that all is working fine now and reopen this issue in
case it is not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/pIew3gH_pf_P3Pp-xFTxfRp4lbtlinp9eSLm79QX67O-hf89lzG3TUMqM-Y3F3NLMnIF10itKL2GdFU1vM-UvFfgq6yb_L7Z6rWGFXJ0M3QIlrz7Eh7haRG6KDuq8TXXoIIA_YCiXJeOO9c_Z3gH_btQdZECLZuKzo4Y9KXVabi73rJAe7X_n5vla90dtBUYTTtJ-fIKgPogztuZkHpP-Ft8XpUTATvYn00aMjdp4g=s0-d-e1-ft#https://github.com/notifications/beacon/AADYYKTRMLCZV5RXFEPRXTTSDSOVBA5CNFSM4QJVZ7DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFDGNEII.gif>

**Comment by espiritocz** [comment]
hi.

I want to inform you that the tool somehow again does not work with the netcdf time.
is it possible that the improved file was overwritten in github? (doprofile.py - last edits are 7 months ago....)

thank you

**Comment by radosuav** [comment]
Hi, the change in is plottingtool.py: https://github.com/DHI-GRAS/qgis-temporal-profile/blob/master/tools/plottingtool.py#L46

Are you using the plugin from QGIS plugin repository or you downloaded it from GitHub. Could you check that line 46 of plottingtool.py is the same as in the link above.

If you still cannot solve this then please send a small netCDF with time dimension which is causing the issue.

**Comment by espiritocz** [comment]
hi Radoslaw,

yes, i installed through QGIS3 repository (qgis version 3.14)
strange - the import is there. this is the error message that i get when
using "Time" -> from NetCDF:

Traceback (most recent call last):
              File
"/home/espi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/temporalprofileplugin.py",
line 176, in leftClicked
              self.doubleClicked(point)
              File
"/home/espi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/temporalprofileplugin.py",
line 181, in doubleClicked
              self.doprofile.calculatePointProfile(point, self.mdl,
self.plotlibrary)
              File
"/home/espi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/tools/doprofile.py",
line 117, in calculatePointProfile
              PlottingTool().attachCurves(self.dockwidget, self.profiles,
model, library)
              File
"/home/espi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/temporalprofiletool/tools/plottingtool.py",
line 155, in attachCurves
              line = wdg.plotWdg.figure.get_axes()[0].plot(xx, yy, gid =
profileId)[0]
              File "/usr/lib/python3/dist-packages/matplotlib/__init__.py",
line 1812, in inner
              return func(ax, *args, **kwargs)
              File
"/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 1612, in
plot
              self.add_line(line)
              File
"/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1895, in
add_line
              self._update_line_limits(line)
              File
"/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1917, in
_update_line_limits
              path = line.get_path()
              File "/usr/lib/python3/dist-packages/matplotlib/lines.py",
line 945, in get_path
              self.recache()
              File "/usr/lib/python3/dist-packages/matplotlib/lines.py",
line 640, in recache
              x = _to_unmasked_float_array(xconv).ravel()
              File
"/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 1365,
in _to_unmasked_float_array
              return np.asarray(x, float)
              File
"/home/espi/.local/lib/python3.7/site-packages/numpy/core/_asarray.py",
line 83, in asarray
              return array(a, dtype, copy=False, order=order)
             TypeError: float() argument must be a string or a number, not
'real_datetime'



I have prepared a crop of my input file - please have a brief look:

https://owncloud.cesnet.cz/index.php/s/ndQgaUNQbr9uNeV/download (it is 90
kB file)


i just import it to QGIS as Raster and select 'cum' (that has the time
coords).


thank you..


Milan




po 14. 9. 2020 v 6:29 odesílatel Radoslaw Guzinski <notifications@github.com>
napsal:

**Comment by radosuav** [comment]
Hi, unfortunately I also couldn't get the plugin to work with your example file. Maybe the calendar used in your file is not supported by nc_time_axis? I don't have much time to spend on this at the moment so for now I will just leave this issue open. If you manage to figure something out (you did get it to work for a while ;) ) then please report it.

**Comment by espiritocz** [comment]
argh,

you're right!
thank you for remark - yes, now it was about the file i prepare. it is
working if i encode the time as integer (dtype='i4')... strange that it
shows error about 'real_datetime'. anyway - it works (again)!

cheers,

M.

čt 17. 9. 2020 v 10:55 odesílatel Radoslaw Guzinski <
notifications@github.com> napsal:

**Comment by radosuav** [comment]
Ok, so I will close the issue :)
