### ISSUE TITLE
Use time dimension on X-axis when available

### ISSUE THREAD

**Issue by radosuav** [DHI-GRAS/qgis-temporal-profile#7]
Feedback from a user:
Let the plugin read 'Time' dimension from raster layers (when supported, like in NetCDF rasters) and give to users the possibility of using time values in the X-axis as an additional option to the raster band number. As an example, 'Time manager' Qgis plugin is reading time information from NetCDF raster.

**Comment by j08lue** [comment]
https://github.com/anitagraser/TimeManager

**Comment by aloboa** [comment]
Please see
https://github.com/anitagraser/TimeManager/issues/204
related to this matter in TimeManager
